name: deployment of django project

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    services:
      postgresql:
        image: postgresql:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверка наличия изменений в репозитории
        uses: actions/checkout@v3

      - name: Установка python и библиотек
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей проекта
        run: pip install -r requirements.txt

      - name: Линтинг
        run: flake8 logistic --exclude logistic/migrations

      - name: Тестирование
        run: python manage.py test

      - name: Деплой
        uses: appleboy/ssh-action@master
        env:
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PASSWORD
          script: expect ~/DRF_2/deploy.exp